source $VIMRUNTIME/defaults.vim

" --------------------
" SOURCE VIMRC ON SAVE 
" --------------------

augroup vimrc
  autocmd! BufWritePost $MYVIMRC source % | echom "Reloaded " . $MYVIMRC | redraw
  autocmd! BufWritePost $MYGVIMRC if has('gui_running') | so % | echom "Reloaded " . $MYGVIMRC | endif | redraw
augroup END

" --------------------
" BASIC SETTINGS
" --------------------

set mouse=a
set encoding=utf-8      " The encoding displayed.
set fileencoding=utf-8  " The encoding written to file.
set hidden
set noswapfile
" create undodir
call mkdir($HOME."/.vim/undo", "p", 0700)
set undodir=$HOME/.vim/undo " needs to exist
set undofile

" MODE
let &t_SI.="\e[5 q" "SI = INSERT mode
let &t_SR.="\e[4 q" "SR = REPLACE mode
let &t_EI.="\e[1 q" "EI = NORMAL mode (ELSE)
"settings:
"  1 -> blinking block
"  2 -> solid block
"  3 -> blinking underscore
"  4 -> solid underscore
"  5 -> blinking vertical bar
"  6 -> solid vertical bar

" STYLE
set background=dark
set termguicolors
set laststatus=2
set number
set relativenumber
set signcolumn=auto   
set listchars+=tab:→\ ,
set listchars+=space:⸱,
set listchars+=nbsp:␣,
set listchars+=eol:↲,
set listchars+=precedes:←,
set listchars+=extends:→,

set splitright
set splitbelow

" INDENT
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap

" SEARCH
"set path+=**        " include subdirectorys
set wildmenu
set wildmode=list:full
"set wildignorecase   " this option breakes NETRW in Termux
set wildignore=node_modules/**,.git/**
set ignorecase
set smartcase
set hlsearch
set showmatch

" --------------------
" STATUS LINE
" --------------------

"function! InsertStatuslineColor(mode)
"  if a:mode == 'i'
"    hi statusline ctermfg=6 ctermbg=0
"  elseif a:mode == 'r'
"    hi statusline ctermfg=5 ctermbg=0
"  else
"    hi statusline ctermfg=1 ctermbg=0
"  endif
"endfunction
"
"au InsertEnter * call InsertStatuslineColor(v:insertmode)
"au InsertLeave * hi statusline ctermfg=8 ctermbg=0
"
"" default the statusline when entering Vim
"hi statusline ctermfg=8 ctermbg=0
"
"" hl-user
"hi User1 ctermfg=8  ctermbg=234

" STATUS
set statusline=%0*                " hl-user
let mybuflisted = {'buflisted':1}
set statusline+=[%n\/\%{len(getbufinfo(mybuflisted))}] " buffer
set statusline+=\ %f\             " file name
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}]           " file format
set statusline+=%y                " filetype
set statusline+=%h                " help file flag
set statusline+=%m                " modified flag
set statusline+=%r                " read only flag
set statusline+=\ %=              " align left
"set statusline+=%1*               " hl-user
set statusline+=\ C:%c            " current column
set statusline+=\ L:%l/%L\ [%p%%] " line X of Y [%]

" --------------------
" Colorscheme
" --------------------

" sainnhe/everforest
"colorscheme everforest
"let g:everforest_transparent_background = 2
"hi StatusLine ctermfg=NONE

" --------------------
" NETRW FILE BROWSER
" --------------------

let g:netrw_browse_split=0
let g:netrw_keepdir=1
let g:netrw_banner=0
let g:netrw_liststyle= 3
let g:netrw_fastbrowse= 2
let g:netrw_winsize=-30
let g:netrw_localcopydircmd='cp -r'

" wipeout netrw buffers when they are hidden
augroup AutoDeleteNetrwHiddenBuffers
  au!
  au FileType netrw setlocal bufhidden=wipe
augroup end

" --------------------
" KEY MAPPING
" --------------------

let mapleader="\<Space>"

" easy prompt access for termux
nnoremap <Leader><Leader> :

" open file explorer
nnoremap <Leader>e :Lexplore<CR>
" open terminal
nnoremap <Leader>t :term<CR>
" disables search highlighting
nnoremap <Esc> :nohlsearch<CR>

" save & quit
nnoremap <Leader>w :write<CR>
nnoremap <Leader>q :quit<CR>

" buffer
nnoremap <Leader>b :ls<CR>
nnoremap <Leader>c :bp\|bd #<CR>

" undo redo
nnoremap <C-Z> u
nnoremap <C-Y> <C-R>
inoremap <C-Z> <C-O>u
inoremap <C-Y> <C-O><C-R>

" Move to window using the <ctrl> hjkl keys
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" resize windows
nnoremap <C-Left> :vertical resize -2<CR>
nnoremap <C-Right> :vertical resize +2<CR>
nnoremap <C-Up> :resize -2<CR>
nnoremap <C-Down> :resize +2<CR>

" jump and center
nnoremap <C-j> <C-d>zz
nnoremap <C-k> <C-u>zz

" better search
nnoremap * *Nzz
nnoremap # #Nzz
nnoremap n nzz
nnoremap N Nzz

" stay in visual mode after indent
vnoremap < <gv
vnoremap > >gv

" regex completion instead of whole word completion
nnoremap <leader>f :find **/*
" restrict the matching to files under the directory
" of the current file, recursively
nnoremap <leader>F :find <C-R>=expand('%:p:h').'/**/*'<CR>

